### ISSUE TITLE
nach Wechsel in umland teilweise keine Grafana Daten mehr

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/meshviewer#12]
hallo,

im umland sind nicht alle Grafana Daten verfügbar.
"node" und auch "node embed" hört nach dem Wechsel einfach auf.
"node graphite" geht auch nach dem wechsel weiter.

Servus
Christian

**Comment by t-offline** [comment]
Danke für Deine E-Mail ("Segm...").
Soviele Infos, prima!
(Kleiner Schreibfehler bei "...Firmware auch selbst unter ...URL ...herunterladen...", da hat sich ein "welcome" imURL eingeschlichen, sollte doch bestimmt "http://firmware.ffmuc.net/umland/stable/" sein.)

Kannst Du, wenn es leicht geht, in den graphite noch die "TRAFFIC" (Delta und Summe) einbauen, oder warten wir lieber auf die ganzheitliche Lösung der nächsten Tage? Wäre für mich auch OK.

Nochmal Danke an alle im Team...
Servus
Christian

**Comment by fpletz** [comment]
Danke für die Info, hab noch eine Mail hintergeschrieben.

Die neuen Statistiken werden demnächst richtig eingebunden.

**Comment by fpletz** [comment]
Alles eingebunden.
