### ISSUE TITLE
simplify cut-and-paste of meshviewer coordinates into configmode

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/meshviewer#13]
moved from https://github.com/freifunkMUC/site-ffm/issues/25

1) provide coordinates in meshviewer (on right click) in '$LAT; $LON' format
2) allow pasting coordinates in the above format into luci, alternatively to using two fields. If first field contains semicolon and second field is empty the string will be split. This should be documented on the wizard page

**Comment by fpletz** [comment]
Also: copy-paste ready uci commands to set the location. :santa:

**Comment by fpletz** [comment]
Fixed with #15.
