### ISSUE TITLE
my node is not reflected on the map since at least weeks

### ISSUE THREAD

**Issue by Giszmo** [freifunkMUC/meshviewer#24]
sorry, I'm not very much into the project but I bought 3 routers and have them running since months. They also were reflected on the map. Mine were the most remote nodes in Chile. I noticed that all "far" nodes were gone at some point, with only few out of Germany popping up again now.

**Comment by fpletz** [comment]
@Giszmo Did you check if they are available on the new map at https://map.ffmuc.net?

If they're running the experimental firmware, they don't have alfred (for distribution infos and stats) included in the firmware anymore. We will release the stable soon and shut down the old map.

**Comment by Giszmo** [comment]
YEAH! Thank you so much. This was it. [Here I am](https://map.ffmuc.net/#!v:m;n:60e3278235a0) :)
