### ISSUE TITLE
default "view" (Vergrößerung) zeigt keine Clients

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/meshviewer#6]
Hallo,
seit der letzten Änderung kommt in der ersten/default Ansicht, oder nach klicken auf einen neuen Knoten immer eine "default view". Diese ist so vergrößert, dass keine clients (Punkte) angezeigt werden. Wer einen Maus mit Rad hat kann/muss zwei Stufen raus zoomen, dann sind die Punkte wieder da. Auch kommt immer die default Karte zur Ansicht, egal was vorher ausgewählt war.
Gibt es einen Weg (z.B. in der url) sowohl der Karte als auch die Vergrößerung dauerhaft festzulegen?

Servus
Christian

**Comment by fpletz** [comment]
Gefixt durch a9d528e6cdd6cd6b25662259e98bae1cc6792d65.
