### ISSUE TITLE
Keine Daten von ffmuc auf http://www.freifunk-karte.de/

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/meshviewer#8]
Hallo,

seit gestern 30.8.2018 ca 21:40 sind keine Knoten von ffmuc mehr dort zu sehen.
Hängt warscheinlich mit dem Wegfall von http://map.freifunk-muenchen.de/list.html zusammen.
Es fehlen die "alten" Daten (nodes_load.json und nodes.json).

Schade!

Servus
Christian

P.S.
Franz: ich habe Dir einige private E-Mails gesendet, kommen diese nicht an?

**Comment by t-offline** [comment]
Hallo,
die Daten die auf https://ffmuc.net/data liegen sind (zumindest bei mir, debian bzw ubuntu) nicht mit "default" abzuholen (wget). Es gibt da ein Problem mit dem COMODO certificate. Kann ich natürlich lokal lösen.
Aber tut das auch http://www.freifunk-karte.de ?

btw:
Der Aufruf (firefox) von https://ffmuc.net/data liefert:
```
Index of /

../
new/                                               31-Aug-2015 00:51                   -
graph.json                                         31-Aug-2015 20:32              125016
nodelist.json                                      31-Aug-2015 20:32              172808
nodes.json                                         31-Aug-2015 20:32             1287788

```
Ein Anklicken geht aber dann nicht (falsche url: https://ffmuc.net/nodes.json richtig wäre: https://ffmuc.net/date/nodes.json).

Servus
Christian

**Comment by fpletz** [comment]
Das mit den falschen Links ist gefixt.

Da ich keinen Code von www.freifunk-karte.de finde kann ich auch nicht nachvollziehen wie das funktioniert. Der Text auf der Webseite ist nicht technisch fundiert genug.

**Comment by t-offline** [comment]
Hallo,
ein: http://www.freifunk-karte.de/debug.php
mit: Meta-Communities "alle zeigen" und Communities "muenchen" gibt:
```
try to find nodeMaps containing [nodeList]-Format
parse as [nodeList]
https://ffmuc.net/data returns no valid json
start parsing
try to find nodeMaps containing any parseable Format
try to find parser for: http://map.freifunk-muenchen.de/
parse as ffmap
http://map.freifunk-muenchen.de/nodes.json returns no valid json
try to find parser for: https://ffmuc.net/data/
no parseable nodeMap found
```
mglw doch was mit dem https.
können wir nicht (nur zum test) mal auch mit http die Daten hinstellen und im api eitragen und dann das debug ansehen ob es dann geht?

P.S.
```
Danke für "alfred158" und "alfred159"; schön wäre noch: "batadv-vis*" und "batctl*" und "alfred160".
```

**Comment by t-offline** [comment]
Nachtrag:
ggf sollte aus dem api: https://raw.githubusercontent.com/freifunkMUC/freifunk.net-API/master/freifunk.net.json
```
  "nodeMaps": [
    {
      "url": "https://ffmuc.net/data",
      "interval": "1 minute",
      "technicalType": "nodelist"
    },
    {
      "url": "http://map.freifunk-muenchen.de",
      "interval": "1 minute",
      "technicalType": "ffmap",
      "mapType": "structural"
    }
  ],
```

auch der "... map.freifunk-muenchen.de..." teil raus.

**Comment by fpletz** [comment]
Habe die nodelist-URL gefixt. Funktioniert jetzt wieder.
