### ISSUE TITLE
new main branch

### ISSUE THREAD

**Issue by T0biii** [freifunkMUC/meshviewer#91]
https://github.com/freifunkMUC/meshviewer/pull/90#issuecomment-2028456013

> i created a new Branch and added there all changes we need for our Meshviewer:
> [new-main](https://github.com/freifunkMUC/meshviewer/tree/new-main?rgh-link-date=2024-03-30T20%3A00%3A15Z)
> 
> if all looks good we should rename the branch to main and rename the old main to something different
> 

the new-main is based on the `upstream/main` and contians our Github Action Deployment and also the EOL Pull Request from grische

**Comment by T0biii** [comment]
CI is passing see: https://github.com/T0biii/meshviewer/actions/runs/8493261695/

**Comment by GoliathLabs** [comment]
Done
